### ISSUE TITLE
Randomly failing SSIM test

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#118]
**Describe the bug**
Test `test_multi_scale_ssim_loss_raise_if_wrong_value_is_estimated_custom_weights` randomly fails.

**To Reproduce**
1. Run tests in you local environment of on GitHub with some [non-related changes](https://github.com/photosynthesis-team/piq/pull/117)
2. Observe the [test failing](https://github.com/photosynthesis-team/piq/runs/819666366) from time to time

**Expected behavior**
Test fails if and only if the implementation of tested functionality is incorrect

**Screenshots**
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/24959314/86049217-6c003f80-ba5a-11ea-8545-920e83eacfae.png">

**Comment by denproc** [comment]
I did some changes to your script and initialised the prediction/target at each iteration.
I tested some functions for 1000 iterations:
❌ test_multi_scale_ssim_raise_if_wrong_value_is_estimated

❌ test_multi_scale_ssim_raise_if_wrong_value_is_estimated_custom_weights

✅ test_multi_scale_ssim_loss_raise_if_wrong_value_is_estimated

✅ test_multi_scale_ssim_loss_raise_if_wrong_value_is_estimated_custom_weights

✅ test_brisque_values_grey

❌ test_brisque_values_RGB
