### ISSUE TITLE
Modify FSIMc and VSI after PyTorch 1.6.0 release

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#121]
**Is your request related to a problem? Please describe.**
Now instead of operations on complex tensors we just take an abs of similarity maps. It's due to PyTorch 1.5.0 and earlier not supporting complex tensor gradients. This problem will be fixed in next release.

**Describe the solution you'd like**
Propose to change this:
```python
        score = score * torch.abs(S_I * S_Q) ** lmbda
```
into this:
```python
        score = score * torch.real((S_I * S_Q).to(torch.complex64) ** lmbda)
```

This will match 100% with original MATLAB code

See #109

**Comment by denproc** [comment]
This one could be also applied to VSI measure to simply code. Current implementation do it explicitly, i.e. translate to complex manually, do operation and return real part. 

Will the implementation depend on the pytorch version? How do you propose to support legacy?

**Comment by francois-rozet** [comment]
Hello @zakajd. As of torch-1.7.1, I believe complex-type powers (still) do not support automatic differentiation.

**Comment by zakajd** [comment]
There are _some_ support for complex grads. Last time I checked it for 1.6 nightly builds and everything work fine with FSIM, but VSI failed. 

https://pytorch.org/docs/stable/notes/autograd.html#complex-autograd-doc

We still need to wait a release or two for it to become stable, so I’ll close this issue and reopen later. 

Also, there are other metrics which may benefit from complex computations, for example SR-SIM and IW-SSIM.

**Comment by francois-rozet** [comment]
@zakajd I believe MDSI also uses `pow_for_complex`, you could add it in the title.
