### ISSUE TITLE
Utils refactoring

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#132]
**Is your feature request related to a problem? Please describe.**
The project becomes more complicated. After each PR it includes new supplementary code. New structure seems to be needed.

**Describe the solution you'd like**

1. Make a `utils` folder
2. Put the `functional.py` here "as is"
3. Rename `utils.py` -> `utils/common.py`
3. Create a new file `utils/layers.py`
4. Add `L2Pool2d` from `perceptual.py` here (from #131)

**Describe alternatives you've considered**
Leave things "as is" or just move `L2Pool2d` to the `functional.py` as @denproc proposed in #131

**Comment by snk4tr** [comment]
@zakajd @denproc please comment on that

**Comment by zakajd** [comment]
I agree that moving functional things into a separate folder is a good idea. 
Let's follow the structure you proposed, it looks reasonable for now.

I already did this in PR with DISTS metric, but we can try to split this into 2 separate PRs with a bit `git` of magic.

**Comment by snk4tr** [comment]
@zakajd you can split things as you like 😄 
Just keep in mind that if one PR corresponds to one feature/bug fix/architecture change then it is just easy to track and understand. It is quite feasible in most cases unless some global refactoring is being done like in case of recent Denis' PR #134

**Comment by denproc** [comment]
Nice idea. I would propose to split the `utils` and `functional`. Utils are for internal usage (it just checks inputs), while functional can provide useful functionality in addition to metrics.
```
piq/piq
    ├── functional
        ├── __init__.py
        ├── colour_conversion.py
        ├── ...
        └── filter.py
    ├── feature_extractors
        └── ...
    ├── utils
        ├── __init__.py
        ├── validation.py # common.py or other title
        └── layers.py # It might be a good idea to have a separate folder with layers
    ├── __init__.py
    ├── base.py
    ├── ...
    └── vsi.py
```
