### ISSUE TITLE
[Query] Why is torch 1.5.0 imposed?

### ISSUE THREAD

**Issue by skat00sh** [photosynthesis-team/piq#143]
In `requirements.txt` the first line `torch>=1.2.0,!=1.5.0` uninstalls existing pytorch version and re-installs this particular version. This could end up in breaking the entire existing pipeline in some case. 
Any particular reason why is this being imposed? 
Is `torch>=1.2.0` already being tried and the results weren't good enough?

**Comment by zakajd** [comment]
Hi!
> Any particular reason why is this being imposed?

Yes, see discussion #79 
PyTorch 1.5 have some issues with backpropagation, which breaks BRISQUE score. 
If you are not using it and installing via `pip`, here is a workaround:
`pip install piq --ignore-installed torch`
