### ISSUE TITLE
Update README with descriptions of competative advantages

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#150]
**Is your feature request related to a problem? Please describe.**
Potential user of the library need to know why would anyone bother to use this. Hence precise description of such advantages is required.

**Describe the solution you'd like**
@zakajd has already given a great number of examples in comments to #148. Take them from here with minor corrections, maybe add more.

**Comment by zakajd** [comment]
Good idea. I would also propose to add a table with list of all metrics and links to original papers. Looks like current structure with nested examples isn't indexed properly by Google or Yandex search engines.

**Comment by snk4tr** [comment]
Sounds good to me. This point can also become a part of the PR closing this issue.
