### ISSUE TITLE
Potential bug in MS-GMSDc

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#161]
**Describe the bug**
It's not a bug report, but more like a potential bug report.
I have a testing pipeline which allows to use metric and compute scores on TID2013 database.

It's common to evaluate metric performance by Spearmank Rank Order Correlation or Kenall Rank Order Correlation.
Values from original paper (mentioned in #67 ):
MS-GMSD - SRCC **0.8139** KROCC **0.6467**
MS-GMSDc - SRCC **0.8895** KROCC **0.7115**
My values: 
MS-GMSD - SRCC **0.811** KROCC **0.643**
MS-GMSDc - SRCC **0.814** KROCC **0.645**

**Expected behavior**
Expected to get values close to original ones. 
Pipeline works fine, because for almost all other metrics I match stated performance

**Additional context**
There is no code from authors to compare with 👎 
So maybe they just did something not mentioned in the paper, thats why results are different

**Comment by denproc** [comment]
A hypothesis: The possible difference is lack of scaling of the inout images to 256 size like it is done for MDSI and VSI.

**Comment by zakajd** [comment]
@denproc  Bingo! It worked. 
New values:
MS-GMSD - SRCC 0.812 KROCC 0.645 
MS-GMSDc - SRCC 0.887 KROCC 0.710
