### ISSUE TITLE
Compare two images

### ISSUE THREAD

**Issue by khawar512** [photosynthesis-team/piq#173]
How to compare two images by giving images link directly?

**Comment by zakajd** [comment]
Hi,
You need to load images as torch.Tensors first and then compare them. 
Try something like this:
```
import piq
from skimage import io
import torch

image1 =  torch.tensor(io.imread(url1))
image2 =  torch.tensor(io.imread(url2))

score = piq.ssim(image1, image2)
```

**Comment by khawar512** [comment]
It gives an error, ValueError, Kernel size cant be greater than actual input size.

**Comment by zakajd** [comment]
This means, that images you trying to pass are too small. Try setting `kernel_size` to a smaller value, or check that images have the right size.

**Comment by khawar512** [comment]
the images are Kodak

**Comment by zakajd** [comment]
What shapes to they have?
Try `print(image1.shape, image2.shape)`

**Comment by khawar512** [comment]
Output
========
torch.Size([512, 768, 3]) torch.Size([512, 768, 3])

Overall code
=========

import piq
from skimage import io
import  torch

image1 = torch.tensor(io.imread("/home/khawar/Desktop/Image-Quality/kodim01.png"))
image2 = torch.tensor(io.imread("/home/khawar/Desktop/Image-Quality/00.png"))

score = piq.ssim(image1,image2)
print(image1.shape, image2.shape)
print(score)

If i put kernel size 1 SSIM value is changed and then i put kernel value 3 then again SSIM changed. I dont know which one is correct

**Comment by zakajd** [comment]
Shape of the input is incorrect. It's written in the docstring, that images must be in channel first order (C, H, W).
Add this before score computation.
```
image1 = image1.permute(2, 0, 1)
image2 = image2.permute(2, 0, 1)
```

**Comment by khawar512** [comment]
Fine. What is correct Kernel size? Because SSIM value is changed according to Kernel size

**Comment by zakajd** [comment]
Default for SSIM is 11, this is value used in most papers.

**Comment by khawar512** [comment]
why my score is in tensor like this tensor(0.2641)?

**Comment by zakajd** [comment]
Because our library works with PyTorch and use Tensors as inputs and returns tensors as outputs.
To convert this value into numpy array simply call `.numpy()` method.

**Comment by khawar512** [comment]
Thank you. problem solve but i am not sure about final value.
