### ISSUE TITLE
Add "PSNR and SSIM alternatives" to README.md

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#185]
**Is your feature request related to a problem? Please describe.**
Most metrics in this library are from research papers and not well-known to the community. 
Thus most popular PSNR and SSIM are keep being reused despite availability of others, more "perceptual" alternatives

**Describe the solution you'd like**
Add something like "If you want to use PSNR for your research, consider this things instead: ..." and a table with comparison on a common IQA dataset (KADID10k / TID2013 / ...). 

**Additional context**
Table to use
<img width="732" alt="image" src="https://user-images.githubusercontent.com/15848838/98597181-a1ab1400-22e9-11eb-9d58-25bd48a17a60.png">

**Comment by snk4tr** [comment]
Related to #207. Closed in favour of #207.
