### ISSUE TITLE
Unify input tensors name

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#192]
**Is your feature request related to a problem? Please describe.**
Currently half of functions take `x` and `y` tensors as inputs, while another part calls them `prediction` and `target`. 

**Describe the solution you'd like**
Let's agree on some fixed naming and refactor all code to be consistent.
I personally  like option with `x` and `y`, which is much shorter. 

@snk4tr @denproc what do you think?

**Comment by snk4tr** [comment]
I also like `x` and `y` option more since it is task independent. We don't actually require these tensors to be prediction and target, they can also be any two tensors.
