### ISSUE TITLE
Access modifiers for feature extraction methods

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#193]
**Is your feature request related to a problem? Please describe.**
Recently, someone had a good point that our feature extraction methods use protected notation even though they are used publicly. Here is the example from our README.md:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/24959314/101798454-2624c880-3b1c-11eb-988c-28e839cd3dae.png">
@zakajd @denproc are you agree that it looks a bit inconsistent and underscores should be removed or am I missing something here?

**Describe the solution you'd like**
Remove underscores from feature extraction methods of feature-dependent metrics.

**Describe alternatives you've considered**
Leave things "as is".

**Comment by zakajd** [comment]
Yeah, we can make them public, no problem. 
I initially made method private to show that it mostly for internal usage. Let's also add documentation on DataLoader structure, because dict output isn't a standard way of dealing with images.

**Comment by snk4tr** [comment]
Indeed, I remember that initially it was not meant to be used externally. You can assign the issue to yourself if you would like to fix it. Otherwise I can do that.
