### ISSUE TITLE
Split code for SSIM and MS-SSIM into separate files

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#203]
**Is your feature request related to a problem? Please describe.**
Right now `piq/ssim.py` is the biggest file in our library with ~600 lines of code. Tests for this file in `tests/test_ssim` also span for ~500 lines of code. We initially combined SSIM and MS-SSIM because they were simular to each other, but now with release of IW-SSIM and SR-SIM metrics it's seems logical to split them. 

**Describe the solution you'd like**
Move all MS-SSIM code into `piq/ms_ssim.py` and all tests into `tests/test_ms_ssim.py`.

**Additional context**
We can do this after all current PR's are merged (#184 #195 #201 #202 ) to avoid confusion.

**Comment by snk4tr** [comment]
I am not sure that splitting up just because of a significant number of lines within a couple of files is the best reason. If entities are coupled it could be good to leave them within a single module other than to introduce new abstractions and imports. What do you think?

**Comment by zakajd** [comment]
Following this logic we need to group IW-SSIM with them, because it's also very similar. 
Let's discuss this on Monday 😄

**Comment by snk4tr** [comment]
Do this after tests are enhanced to make sure that results are not broken.

**Comment by zakajd** [comment]
@denproc I reassigned this to myself, if you don't mind.
Will close it together with #209
