### ISSUE TITLE
Add benchmark code for PLCC, SRCC, KRCC evaluation on MOS databases.

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#207]
**Is your feature request related to a problem? Please describe.**
Now this code is available only for me and @snk4tr as part of another project. Propose to simplify it and add as a standalone script into the library, so that everyone could verify metric performance.

**Describe the solution you'd like**
Add `benchmark.py` file into `tests` folder with support for TID2013 and KADID10k databases evaluation.
Create README section with results.

**Additional context**
I've run all the tests locally and it seems that not all implementations from our library are now consistent with results from papers. Here is table for TID2013 database
<img width="1290" alt="Screenshot 2021-01-15 at 12 50 57" src="https://user-images.githubusercontent.com/15848838/104709887-7a7d2280-5730-11eb-885a-ee2237c27cba.png">

**Comment by snk4tr** [comment]
Great initiative! Love that!

**Comment by snk4tr** [comment]
Other possible namings are: `computational_correctness_benchmark.py` or just `correctness_benchmark.py`.

**Comment by snk4tr** [comment]
As discussed with @zakajd and @denproc please also reduce number of shield on the top of the `README.md` file. I think it can be done as a part of a PR accommodating this issue.
