### ISSUE TITLE
Metric: WaDIQaM and DIQaM

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#223]
**Is your feature request related to a problem? Please describe.**
It seems that this measure performs great on dataset with GAN distortions, so adding it here can be a valuable contribution to fasten the research process.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/15848838/106353429-8c97bd00-62fb-11eb-97a7-7f782b5e4cac.png">

**Describe the solution you'd like**
Medium link with simplified explanation: https://sh-tsang.medium.com/reading-diqam-wadiqam-weighted-average-deep-image-quality-measure-image-quality-assessment-1ea4cf1d37e0
Original WaDIQaM repo (PyTorch sic!): https://github.com/lidq92/WaDIQaM

It seems that DIQaM is same as deepIQA (#222), but need to verify that

**Comment by Shamus98** [comment]
I took this issue

**Comment by snk4tr** [comment]
Closed due to duplication with #222
