### ISSUE TITLE
While data range -1 1 this code can't work 

### ISSUE THREAD

**Issue by Linaom1214** [photosynthesis-team/piq#235]
When  my image data in range -1 to 1 ,this code seem can't work

**Comment by zakajd** [comment]
Hi @Linaom1214 
What metric are you trying to use?
We constrained value range requirements because most of the metrics was initially proposed and tuned for [0, 1] data range.

**Comment by Linaom1214** [comment]
> Hi @Linaom1214
> What metric are you trying to use?
> We constrained value range requirements because most of the metrics was initially proposed and tuned for [0, 1] data range.

In a GAN model the output range usually is [-1 1] because the last layer is 'tanh'

**Comment by snk4tr** [comment]
Hi @Linaom1214. 
It really depends on the GAN model of choice. Consider replacing `tanh` with some other non-linearity. 
The question asked by @zakajd on what metric you try to use is quite important because some of them are undefined for tensors with negative values. It would also be great it you could provide a stack trace showing the error you get.

**Comment by Linaom1214** [comment]
> Hi @Linaom1214. 
> 
> It really depends on the GAN model of choice. Consider replacing `tanh` with some other non-linearity. 
> 
> The question asked by @zakajd on what metric you try to use is quite important because some of them are undefined for tensors with negative values. It would also be great it you could provide a stack trace showing the error you get.

  Oh thanks ,in many model they use the tanh layer because this layer can make your work more efficient.

**Comment by zakajd** [comment]
Hi @Linaom1214 
We merged an update yesterday, which makes assertions optional.
1. You can run the code with `-O` python flag to disable all asserts.
2. _Alternatively_, passing **negative** value for `data_range` parameter will disable check only for value ranges. Note, that metrics predictive performance will likely drop or fail completely. 

I'll close the issue, feel free to open another one if needed.

**Comment by michaelstuffer98** [comment]
Hi @zakajd , I came across this issue and have a question regarding two metrics: SSIM and GMSD. Can you clarify if I can use these measures with negative values? I use ViT MAE

**Comment by zakajd** [comment]
Hi @michaelstuffer98 
No, both SSIM and GMSD require input tensors to be in a positive range (usually [0, 1] or [0, 255]).
You can add a simple rescaling before passing images to the metric by doing: `x_scaled =  (x + 1) * 0.5`. This will shift the range from [-1, 1] to [0, 1].

Hope it's helped!
