### ISSUE TITLE
SSIM attained different SRCC/KRCC scores

### ISSUE THREAD

**Issue by vztu** [photosynthesis-team/piq#248]
**Describe the bug**
SSIM attained different SRCC/KRCC (see below). Can reproduce the results of all other metrics.

**To Reproduce**
1. `pip install piq` (My version: piq==0.5.4)
2. `git clone https://github.com/photosynthesis-team/piq.git`
3. `python3 tests/results_benchmark.py --dataset tid2013 --metrics SSIM --path ~/datasets/tid2013 --batch_size 16
`
4. `python3 tests/results_benchmark.py --dataset kadid10k --metrics SSIM --path ~/datasets/kadid10k --batch_size 16
`

**Expected behavior**
Help on this bug

**Screenshots**
_stdout_:
```
Parameters used for benchmark: Namespace(batch_size=16, dataset='tid2013', device='cuda', metrics=['SSIM'], path=PosixPath('data/tid2013'))
SSIM: SRCC 0.5544 KRCC 0.3883
```
```
Parameters used for benchmark: Namespace(batch_size=16, dataset='kadid10k', device='cuda', metrics=['SSIM'], path=PosixPath('data/kadid10k'))
SSIM: SRCC 0.6329 KRCC 0.4571
```

**Additional context**

**Comment by zakajd** [comment]
Hi, thanks for reporting the bug.
I've tried to replicate you results, but got correct values: 
```
Namespace(batch_size=16, dataset='tid2013', device='cuda', metrics=['SSIM'], path=PosixPath('~/data/tid2013'))
SSIM: SRCC 0.7201 KRCC 0.5271

 Namespace(batch_size=16, dataset='kadid10k', device='cuda', metrics=['SSIM'], path=PosixPath('~/data/kadid10k'))
SSIM: SRCC 0.7242 KRCC 0.5370
```

Actually, your results is what I get with `downsample=False` flag in SSIM metric, so check that you are using correct version of the library.

**Comment by vztu** [comment]
Hi thanks @zakajd! I have reinstalled the newest version (compiled from Master branch) and the bug was fixed. 

However, I encountered another bug with FSIM and VSI:
```
AttributeError: module 'torch.fft' has no attribute 'fft2'
```

My torch version is `1.7.1` but couldn't get this work.

**Comment by zakajd** [comment]
@denproc you was the author of PR which introduced different behaviour depending on torch version. 
Can you help with this?

**Comment by denproc** [comment]
Hi @vztu, thanks for raising the issue. `torch==1.7` appears to have only `fftn` functionality and miss `fft2`, which was introduced only with `1.8.0` version. I'll create the PR to fix this.
