### ISSUE TITLE
Haar psi coefficients shape

### ISSUE THREAD

**Issue by Jagdeep-uad** [photosynthesis-team/piq#257]
**Describe the bug**
The shape of coefficients generated in HaarPSI are **(N, {scales * 2}, H/2, W/2)** instead of **(N, {scales * 2}, H, W)**

**To Reproduce**
in the function HaarPSI after the  x and y coefficients are calculated, printing the shape of coefficients_x, coefficients_y returns the shape **(N, {scales * 2}, H/2, W/2)** 

**Expected behavior**
should return shape **(N, {scales * 2}, H, W)** instead.

**Comment by zakajd** [comment]
Hi @Jagdeep-uad 
Please see [original paper](https://arxiv.org/pdf/1607.06140.pdf)  page 10
<img width="701" alt="image" src="https://user-images.githubusercontent.com/15848838/122366609-600bd700-cf64-11eb-8b74-eeafe66f877c.png">

You can disable this behaviour by passing `subsample=False` to `haarpsi` or `HaarPSILoss`
