### ISSUE TITLE
Measure: Perceptual Scores

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#26]
**Is your feature request related to a problem? Please describe.**
Need to add two types of perceptual scores: content score and style score. Both scores might be needed both and measures and as losses.

**Describe the solution you'd like**
Add both measures based on implementation by @zakajd. Improvements to be made:
- Readable layer names. They are needed for better understanding of what layers are used.
- Normalization of values in layers if several layers are used.

**Comment by zakajd** [comment]
I also suggest to add code from this [repo](https://github.com/richzhang/PerceptualSimilarity), which is PyTorch implementation of paper proposing [LPIPS](http://arxiv.org/abs/1801.03924).

**Reason**: In case of fixed weights LPIPS is identical to vanilla VGG perceptual score.

**Comment by snk4tr** [comment]
@zakajd, in general, I think that addition of LPIPS is a good idea. However, I also think that it should be a different metric placed in a different file, which can call PS if needed to avoid code duplication. If you consider adding LPIPS later, please create the corresponding issue and implement this is a separate PR.
