### ISSUE TITLE
Conda package version is not updated 

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#260]
**Describe the bug**
Conda version is not updated in conda repository after the last release (0.5.5).

**Expected behavior**
- Release for conda is updated as well as it is updated for pypi;
- Version in the badge is changed;
- Update is provided with the CD pipeline.

**Screenshots**
![image](https://user-images.githubusercontent.com/24959314/127523925-4f2cb36c-4cdc-4f78-81cc-a165f92155b6.png)

**Additional context**
@denproc it would be great if you could have a look when/if have time since you implemented the conda deployment CD pipeline.

**Comment by denproc** [comment]
Updated expired Conda token to upload packages. Release 0.5.5 added to [anaconda](https://anaconda.org/photosynthesis-team/piq). 
The badge should be updated within 24 hours.
