### ISSUE TITLE
How can I load image with extension '.png', '.jpg' in image_metrics.py code??

### ISSUE THREAD

**Issue by thanhtung0406** [photosynthesis-team/piq#274]
I want to read image .png and .jpg then calculate quality image metrics. Please help me

![image](https://user-images.githubusercontent.com/11147205/139654820-0e802a9d-27db-4587-8fa9-c05cd802c185.png)
![image](https://user-images.githubusercontent.com/11147205/139654885-58dd84a0-e6fb-4194-b4a6-dc3422b727ca.png)

**Comment by zakajd** [comment]
You are using both `np.expand_dims` and `[None, ...]` syntax, so your final image shape is (1, 1, C, H, W). 
Also it seems that your screenshots have 4 channels, while image is expected to have only 3 (R, G, B).
