### ISSUE TITLE
Benchmark request

### ISSUE THREAD

**Issue by pythonmobile** [photosynthesis-team/piq#297]
PIQA claims that it is faster that piq. Has anyone done a benchmark against these two libraries using SSIM? Perhaps someone can shed some light on that: 

Related: https://github.com/francois-rozet/piqa/issues/23

**Comment by snk4tr** [comment]
Hi @pythonmobile. 
We have not done an extensive comparison of such. However, you can have a look at the [table](https://github.com/photosynthesis-team/piq/issues/212#issuecomment-767075105) that we made to compare several implementation options. What you can see here are relative execution times when all required checks are used (our implementation, column **time -O**) and no checks are used (the closest to the PIQA implementation, **time no validation + no adjust** column). Note that the difference is marginal and should not be critical for most practical applications. 
Feel free to reopen in case of additional questions.
