### ISSUE TITLE
Discrepancy between Torchvision versions in requirements.txt and meta.yaml

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#299]
**Describe the bug**
There are known problems with library usage with `Torchvision<0.6.1`, however `Torchvision>=0.4.0` is allowed for a user setup.

**Expected behavior**
The same version is used in both cases.

**Comment by denproc** [comment]
I suggest to extend this issue to upgrade of `torchvision` and python versions used in testing pipelines.
Let's update:
- `torchvision` version to `0.11.0` in GitHub pipeline
- `python` version to `3.10`
