### ISSUE TITLE
Metric: Sum of gaussian derivatives

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#34]
**Is your feature request related to a problem? Please describe.**
Implement metric described in [the paper](http://amnl.mie.utoronto.ca/data/J25.pdf).

**Describe the solution you'd like**
Fix existing implementation or add a custom one.

**Comment by zakajd** [comment]
Let's close this issue as not relevant anymore, because gaussian derivatives metric is similar to GMSD without pooling.
