### ISSUE TITLE
Support weighted SSIM and MS-SSIM losses

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#5]
**Is your feature request related to a problem? Please describe.**
First implementation of SSIM and MS-SSIM losses will be basic, treating each element of the batch equally. However, a user may want to weight items within batch as it can be done in `BCELoss` and[ some other losses in PyTorch](https://pytorch.org/docs/stable/nn.html).

**Describe the solution you'd like**
First, implement `_WeightedLoss` interface. Keep it protected since it is not supposed to be publicly accessed and only supposed to be used for the inheritance reasons. Take `_WeightedLoss` [implementation in PyTorch](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/loss.py) as a reference

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by francois-rozet** [comment]
Hello @snk4tr, an easy alternative to specializing SSIM and MS-SSIM could be to create a super class of the current ones that requires a vector of weights.

Another way could be to implement the class `WeightedLoss` as a wrapper. It would be initialized with any instantiated `_Loss`  (with `reduction=none`) as argument and its forward pass would relay the inputs to the loss and then  weight the output of the loss.

**Comment by snk4tr** [comment]
Closed after discussion with @zakajd and @denproc due to low priority.
The idea has a potential but need more research.
