### ISSUE TITLE
Blind image quality metrics request

### ISSUE THREAD

**Issue by PavelOstyakov** [photosynthesis-team/piq#80]
Hi, thank you for your awesome work. I do like the idea of combining many metrics in one place.

In the future, it will be great to see implementations of some image quality metrics from https://github.com/dsoellinger/blind_image_quality_toolbox

So, I hope they can be ported to PyTorch and I will not have to run Matlab :)

**Comment by snk4tr** [comment]
Hi @PavelOstyakov. 
We are planning to integrate some of them in the nearest future. For instance, BRISQUE is currently under development (#79) and going to be merged soon. Any feedback or contribution regarding this or any other measure/metric is highly appreciated 😄

**Comment by snk4tr** [comment]
@zakajd will select several top performing metrics according to recent papers and open new feature request issue for each of them.

**Comment by zakajd** [comment]
Added separate issues for No-Reference metrics that we consider important. 
Closing this one
